<?php

namespace App\Utils;

class Util
{
    public function  dealers($is_all = false){

         $dealers = collect([
            [ "link" => "https://share.google/1x5tgCAIrKxxRFmu2", "image" => "images/wholesalers/dona.webp", "name" => "La Doña Market", "phone"=> "+1 720-531-4569", "adress" => "2420 E Midway Blvd D, Denver, CO 80234" ],
            [ "link" => "https://g.co/kgs/V5Hr3XR", "image" => "/images/distribuidor/abarrotes-y-carniceria-la-bikina.webp", "name" => "Abarrotes Y Carnicería La Bikina", "phone"=> "(720) 800-3804", "adress" => " 804 Denver Ave unit b.Fort LuptonCO80203" ],
            [ "link" => "https://g.co/kgs/tn2diZd", "image" => "/images/distribuidor/100-de-gave.webp", "name" => "100% de Agave", "phone"=> "(303) 731-1100", "adress" => " 975 Lincoln St, Denver, CO 80203" ],
            [ "link" => "https://g.co/kgs/m5MaqBg", "image" => "images/distribuidor/carniceria-hernandez.webp", "name" => "Carniceria Hernandez", "phone"=> "(303) 484-9576", "adress" => "5 Federal Blvd.DenverCO80219" ],
            [ "link" => "https://g.co/kgs/CddhWWX", "image" => "images/distribuidor/carniceria-guanajuato.webp", "name" => "Carniceria Guanajuato", "phone"=> "(720) 749-4961", "adress" => "1664 Main St, .LongmontCO80501" ],
            [ "link" => "https://g.co/kgs/jzxfbhV", "image" => "images/distribuidor/tacos-selene-denver.webp", "name" => "Tacos Selene Denver", "phone"=> "(720) 749-4961", "adress" => "1001 Santa Fe Dr, Denver, CO 80204" ],
            [ "link" => "https://g.co/kgs/ZzAsdYs", "image" => "images/distribuidor/tacos-y-tortas-valentin.webp", "name" => "Tacos Y Tortas Valentin", "phone"=> "(720) 633-4503 ", "adress" => "9698 E Montview Blvd, Aurora, CO 80010" ],
            [ "link" => "https://g.co/kgs/etu5unq", "image" => "images/distribuidor/carniceria-la-misma-vaca.webp", "name" => "Carniceria La Misma Vaca", "phone"=> "(719) 573-4700", "adress" => "217 N Academy Blvd.Colorado SpringsCO80909 " ],
            [ "link" => "https://g.co/kgs/h6G6634", "image" => "images/distribuidor/la-sierrita-mexican-grill.webp", "name" => "La Sierrita Mexican Grill", "phone"=> "(719) 696-9055", "adress" => "1200 E Evans Ave, Pueblo, CO 81004" ],
            [ "link" => "https://g.co/kgs/Jc4iWKF", "image" => "images/distribuidor/rancho-alegre.webp", "name" => "Rancho Alegre", "phone"=> "(720) 748-2571", "adress" => "420 S Chambers Rd, Aurora, CO 80017 " ],
            [ "link" => "https://g.co/kgs/yFErBgN", "image" => "images/distribuidor/tortilleria-la-amapola.webp", "name" => "Tortilleria La Amapola", "phone"=> "(720) 255-2927", "adress" => "15376 E Alameda Pkwy, Aurora, CO 80017" ],
            [ "link" => "https://g.co/kgs/R3uioXd", "image" => "images/wholesalers/carniceria_y_abarrotes_chihuas.webp", "name" => "Carniceria Y Abarrotes Chihuas", "phone"=> "(303) 498-0148", "adress" => "1135 E Bridge St.BrightonCO80601" ],
            [ "link" => "https://g.co/kgs/5jsyBz9", "image" => "images/wholesalers/carniceria_la_consetida.webp", "name" => "Carniceria La Consetida", "phone"=> "(303) 341-0044", "adress" => "11651 E Montview Blvd, Aurora, CO 80010" ],
            [ "link" => "https://g.co/kgs/in5CLDA", "image" => "images/wholesalers/la_superior_meat_market.webp", "name" => "La Superior Meat Market", "phone"=> "(303) 344-0022", "adress" => "1020 S Peoria St, Aurora, CO 80012" ],
            [ "link" => "https://g.co/kgs/xFZXBCB", "image" => "images/wholesalers/mercado_la_perla.webp", "name" => "Mercado La Perla", "phone"=> "(970) 368-6767", "adress" => "1161 Blue River Pkwy, Silverthorne, CO 80498" ],
            [ "link" => "https://g.co/kgs/SPsfjqr", "image" => "images/wholesalers/great_wall_supermarket.webp", "name" => "Great Wall Supermarket", "phone"=> "(303) 936-4845", "adress" => "2200 W Alameda Ave #2B, Denver, CO 80223" ],
            [ "link" => "https://g.co/kgs/XdtkTKA", "image" => "images/wholesalers/el_mero_mero_2.webp", "name" => "EL MERO Mero #2", "phone"=> "(970) 785-1148", "adress" => "340 Justin Ave, Platteville, CO 80651 " ],
            [ "link" => "https://g.co/kgs/gSviS5X", "image" => "images/wholesalers/el_mero_mero.webp", "name" => "El Mero Mero", "phone"=> "(970) 301-4718", "adress" => "1002 25th Ave, Greeley, CO 80634" ],
            [ "link" => "https://g.co/kgs/2iHCvG1", "image" => "images/wholesalers/carniceria_el_cerrito.webp", "name" => "Carniceria El Cerrito", "phone"=> "(303) 834-9172 ", "adress" => "936 Maim St.LongmontCO80501" ],
            [ "link" => "https://g.co/kgs/ENNaMtZ", "image" => "images/wholesalers/la_barata_2.webp", "name" => "La Barata #2", "phone"=> "(970) 980-6154", "adress" => "1001 N College Ave, Fort Collins, CO 80524" ],
            [ "link" => "https://g.co/kgs/No6tzcd", "image" => "images/wholesalers/carniceria_la_barata.webp", "name" => "Carniceria La Barata", "phone"=> "(720) 204-6092", "adress" => "1730 Emery St,LongmontCO80501" ],
            [ "link" => "https://g.co/kgs/FbaBzMd", "image" => "images/wholesalers/el_rodeo_meat_market.webp", "name" => "El Rodeo Meat Market", "phone"=> "(719) 543-7476", "adress" => "1301 Lake AvePuebloCO81004" ],
            [ "link" => "https://g.co/kgs/kXUceUd", "image" => "images/wholesalers/carniceria_el _guerrero.webp", "name" => "Carnicería el Guerrero INC", "phone"=> "(303) 644-3161", "adress" => "100 S 1st St.BennettCO80102" ],
            [ "link" => "https://g.co/kgs/JH7Z2FX", "image" => "images/wholesalers/anita_carniceria.webp", "name" => "Anita Carniceria", "phone"=> "(720) 535-1015 ", "adress" => "2863 E 120 Ave.ThorntonCO80233" ],
            [ "link" => "https://g.co/kgs/XABqQoP", "image" => "images/wholesalers/carniceria_tarahuamara.webp", "name" => "Carniceria Tarahumara", "phone"=> " (303) 287-6319", "adress" => "8993 Washington St, Denver, CO 80229" ],
            [ "link" => "https://www.latarahumaramarket.com/", "image" => "images/wholesalers/la_tarahumara_market.webp", "name" => "La Tarahumara Marke", "phone"=> "(970) 356-0435", "adress" => "1101 8th Ave, Greeley, CO 80631" ],
            [ "link" => "https://g.co/kgs/TDLK9vP", "image" => "images/wholesalers/catrina_market.webp", "name" => "Catrina Market", "phone"=> "(303) 936-0341", "adress" => "490s S Federal Blvd, Denver, CO 80219" ],
            [ "link" => "https://g.co/kgs/Pd76E1v", "image" => "images/wholesalers/la_poblanita.webp", "name" => "La Poblanita frutas, verduras y abarrotes", "phone"=> "(720) 933-2883", "adress" => "1830 W 92nd Ave, Federal Heights, CO 80260 " ],
            [ "link" => "https://g.co/kgs/kWqFLKK", "image" => "images/wholesalers/la_morena_mexica.webp", "name" => "La Morena Mexican Restaurant", "phone"=> "(720) 324-8435 ", "adress" => " 9650 E Colfax Ave, Aurora, CO 80010" ],
            [ "link" => "https://g.co/kgs/aPohXVN", "image" => "images/wholesalers/la_morena_mexica_2.webp", "name" => "La Morena Mexican Restaurant 2", "phone"=> "(303) 751-2561", "adress" => " 13800 E Mississippi Ave, Aurora, CO 80012" ],
            [ "link" => "https://g.co/kgs/gCiMbj7", "image" => "images/wholesalers/los_gallitos_taqueria.webp", "name" => "Los Gallitos Taqueria", "phone"=> "(303) 427-7300 ", "adress" => "7101 N Pecos St, Denver, CO 80221 " ],
            [ "link" => "https://g.co/kgs/Cn8rDiV", "image" => "images/wholesalers/taqueria_los_gallitos.webp", "name" => "Taqueria Los Gallitos", "phone"=> "(303) 955-0175 ", "adress" => "2630 W Alameda Ave, Denver, CO 80219" ],
            [ "link" => "https://g.co/kgs/YhsWvc9", "image" => "images/wholesalers/los_gallitos.webp", "name" => "Los Gallitos", "phone"=> "(720) 353-4567", "adress" => "7255 E 72nd Ave, Commerce City, CO 80022" ],
            [ "link" => "https://g.co/kgs/Ak6JDPi", "image" => "images/wholesalers/el_aguascalientes_mexican_2.webp", "name" => "El Aguascalientes Mexican Restaurant", "phone"=> "(303) 463-2833 ", "adress" => "4105 Wadsworth Blvd, Wheat Ridge, CO 80033" ],
            [ "link" => "https://g.co/kgs/xDvUv9o", "image" => "images/wholesalers/el_aguascalientes_mexican.webp", "name" => "El Aguascalientes Mexican Restaurant", "phone"=> "(303) 637-7500", "adress" => "644 S Main St, Brighton, CO 80601" ],
            [ "link" => "https://g.co/kgs/bd2rqUq", "image" => "images/wholesalers/el_rinconcito_hondureno.webp", "name" => "El Rinconcito Hondureño", "phone"=> "(720) 524-4953", "adress" => "el rinconcito hondureñoaurora80011" ],
            [ "link" => "https://www.mariscosuruapan.net/", "image" => "images/wholesalers/mariscos_uruapan.webp", "name" => "Mariscos Uruapan", "phone"=> "(303) 344-0022", "adress" => "1465 N, 1465 Dayton St, Aurora, CO 80010" ],
            [ "link" => "https://g.co/kgs/tvMPxx9", "image" => "images/wholesalers/el_charro_market.webp", "name" => "El Charro Market", "phone"=> "(303) 658-0394", "adress" => "6155 E 72nd Ave,Commerce CityCO80022" ],
            [ "link" => "https://g.co/kgs/y2nBSAL", "image" => "images/wholesalers/carniceria_la_luz.webp", "name" => "Carniceria La Luz", "phone"=> "(303) 373-4515 ", "adress" => "4701 Peoria St,DenverCO80239" ],
            [ "link" => "https://g.co/kgs/5JeJt5Y", "image" => "images/wholesalers/taqueria_los_gallitos_thornton.webp", "name" => "Taqueria Los Gallitos Thornton", "phone"=> "(303) 953-0544", "adress" => "8623 Washington St, Thornton, CO 80229" ],
            [ "link" => "https://g.co/kgs/q746u5N", "image" => "images/wholesalers/carniceria_la_preferida.webp", "name" => "Carniceria La Preferida LLC", "phone"=> "(970) 573-5174", "adress" => "3487 W 10th St AGreeleyCO80634" ],
            [ "link" => "http://orderabuelitasempanadas.com/", "image" => "images/wholesalers/abulita.webp", "name" => "Abuelita's Empanadas", "phone"=> "+1 720-218-9808", "adress" => "332 Main St, Longmont, CO 80501" ],
            [ "link" => "https://www.amamodernmexican.com/", "image" => "images/wholesalers/ama.webp", "name" => "Amá Modern Mexican", "phone"=> "+1 720-352-0738", "adress" => "3200 N Pecos St #202, Denver, CO 80211" ],
            [ "link" => "https://maps.app.goo.gl/jbzK2RiN1wgFh7iFA", "image" => "images/wholesalers/beltran.webp", "name" => "Beltran's Meat Market", "phone"=> "+13032807293", "adress" => "11920 Washington St, Northglenn, CO 80233" ],
            [ "link" => "https://share.google/Iu1vhMzU6rOBitYUN", "image" => "images/wholesalers/arash.webp", "name" => "Arash International Market", "phone"=> "+13037529272", "adress" => "2720 S Parker Rd, Aurora, CO 80014" ],
            [ "link" => "https://share.google/OaNDBwqdLq10G6TWr", "image" => "images/wholesalers/3hermanos.webp", "name" => "Fruteria Y Carniceria 3 Hermanos", "phone"=> "+1 303-857-2223", "adress" => "733 Denver Ave, Fort Lupton, CO 80621" ],
            [ "link" => "https://share.google/D9qh2knCBRpRoMfnq", "image" => "images/wholesalers/chihuahua.webp", "name" => "Carniceria Chihuahua", "phone"=> "+1 720-550-7124", "adress" => "1495 US-287, Broomfield, CO 80020" ],
            [ "link" => "https://share.google/5dE6UvVcMYpFBhDQn", "image" => "images/wholesalers/dariana.webp", "name" => "Carniceria Dariana", "phone"=> "+1 303-750-2302", "adress" => "12028 E Mississippi Ave Unit B, Aurora, CO 80012" ],
            [ "link" => "https://share.google/PqQNhKwryH0gcd5Kt", "image" => "images/wholesalers/elprimo.webp", "name" => "Carniceria El Primo", "phone"=> "+1 720-809-5158", "adress" => "11078 Cimarron St E, Longmont, CO 80504" ],
            [ "link" => "https://share.google/JkgUuoAvnkvbtKBTy", "image" => "images/wholesalers/guadalajara.webp", "name" => "Carniceria Guadalajara", "phone"=> "+1 303-343-0390", "adress" => "1544 Lima St, Aurora, CO 80010" ],
            [ "link" => "https://share.google/pOiLwj0LrWUCWnlTs", "image" => "images/wholesalers/jalisco.webp", "name" => "Carniceria Jalisco", "phone"=> "+1 303-296-0168", "adress" => "3300 N Downing St, Denver, CO 80205" ],
            [ "link" => "https://antojitosdelsureste.com/taft/index.html", "image" => "images/wholesalers/sureste.webp", "name" => "Antojitos del Sureste", "phone"=> "+1 970-617-7279", "adress" => "4001 S Taft Hill Rd, Fort Collins, CO 80526" ],
            [ "link" => "https://www.lapraderacarniceria.net/", "image" => "images/wholesalers/pradera.webp", "name" => "Carniceria La Pradera", "phone"=> "+1 303-227-1475", "adress" => "5640 E 64th Ave, Commerce City, CO 80022" ],
            [ "link" => "https://share.google/9dvTfMSXYGZQamR08", "image" => "images/wholesalers/sierra.webp", "name" => "Carniceria La Sierra", "phone"=> "+1 303-935-6293", "adress" => "3170 W Alameda Ave, Denver, CO 80219" ],
            [ "link" => "https://share.google/xbZqkD3Sixiguqygu", "image" => "images/wholesalers/suprema.webp", "name" => "Carnicería La Suprema", "phone"=> "+1 303-728-9218", "adress" => "9299 Federal Blvd, Westminster, CO 80260" ],
            [ "link" => "https://share.google/q1HMTf1EiX6WHhvUL", "image" => "images/wholesalers/zacatecana.webp", "name" => "Carniceria La Zacatecana", "phone"=> "+1 303-954-8747", "adress" => "4483 Broadway, Boulder, CO 80304" ],
            [ "link" => "https://share.google/gNZTKpndJHScnADv9", "image" => "images/wholesalers/latina.webp", "name" => "Carniceria Latina", "phone"=> "+1 303-283-6844", "adress" => "2272 S Chambers Rd, Aurora, CO 80014" ],
            [ "link" => "https://share.google/twNhBlU5LHVssSQ0y", "image" => "images/wholesalers/michoacanos.webp", "name" => "Carniceria Los Michoacanos", "phone"=> "+1 720-216-0212", "adress" => "800 Dayton St, Aurora, CO 80010" ],
            [ "link" => "https://tapatiossupermeatm.wixsite.com/tapatiossupermarket", "image" => "images/wholesalers/tapatios.webp", "name" => "Carniceria los Tapatios #2", "phone"=> "+1 720-638-5635", "adress" => " 1770 W Mississippi Ave, Denver, CO 80223" ],
            [ "link" => "https://share.google/Rx84fU1JF1cgUuKBs", "image" => "images/wholesalers/sanchez.webp", "name" => "Carniceria Sanchez", "phone"=> "+1 303-295-1156", "adress" => "2630 E 46th Ave, Denver, CO 80216" ],
            [ "link" => "https://www.carniceriasantarosalia.com/", "image" => "images/wholesalers/santa_rosa.webp", "name" => "Carniceria Santa Rosalia", "phone"=> " +1 720-216-0607", "adress" => "1456 W 104th Ave, Northglenn, CO 80234" ],
            [ "link" => "https://share.google/rAUocWxdNPDp6rf2i", "image" => "images/wholesalers/sin_frontera.webp", "name" => "Carniceria Sin Fronteras", "phone"=> "+1 720-866-8824", "adress" => "2283 S Monaco St Pkwy #100, Denver, CO 80222" ],
            [ "link" => "https://www.dannystacosytortas.com/", "image" => "images/wholesalers/dannys.webp", "name" => "Dannys Tacos", "phone"=> "+1 720-317-4397", "adress" => "1751 Hover St, Longmont, CO 80501" ],
            [ "link" => "https://share.google/3phi9tHjS6dPxutVk", "image" => "images/wholesalers/denver.webp", "name" => "Denver Market", "phone"=> "+1 303-339-0303", "adress" => " 1700 W 40th Ave, Denver, CO 80211" ],
            ["link" => "https://share.google/LEpgLie2UbexQyi33", "image" => "images/wholesalers/paola.webp", "name" => "Dulceria Paola LLC", "phone"=> "+1 303-366-9806", "adress" => "1350 Chambers Rd Ste 101, Aurora, CO 80011" ],
            ["link" => "https://www.elburritocojo.com/", "image" => "images/wholesalers/burrito.webp", "name" => "El Burrito Cojo", "phone"=> "+1 303-922-3262", "adress" => "274 S Sheridan Blvd, Denver, CO 80226" ],
            ["link" => "https://share.google/AOCy30i54ZefDTfcf", "image" => "images/wholesalers/charrito.webp", "name" => "El Charrito Market", "phone"=> "+1 970-262-7615", "adress" => "301 Adams Ave, Silverthorne, CO 80498" ],
            ["link" => "https://www.eljakalitocarniceria.com/", "image" => "images/wholesalers/jakalito.webp", "name" => "El Jakalito Market", "phone"=> "+1 303-696-9047", "adress" => "2260 S Quebec St Unit 1, Denver, CO 80231" ],
            ["link" => "https://mercaditotixca.com/", "image" => "images/wholesalers/tixca.webp", "name" => "El Mercado de Tixca", "phone"=> "+1 720-612-4654", "adress" => "6501 E 64th Ave, Commerce City, CO 80022" ],
            ["link" => "https://nopalneveria.com/", "image" => "images/wholesalers/nopal.webp", "name" => "El Nopal Neveria and Café", "phone"=> "", "adress" => "1702 S Chambers Rd, Aurora, CO 80017" ],
            ["link" => "https://share.google/E42lWuuEBUlgH4YC6", "image" => "images/wholesalers/rey_taco_1.webp", "name" => "El Rey del Taco 1", "phone"=> "+1 719-550-4272", "adress" => "522 S Academy Blvd, Colorado Springs, CO 80910" ],
            ["link" => "https://elreydel.top/", "image" => "images/wholesalers/rey_taco_2.webp", "name" => "El Rey del Taco 2", "phone"=> " +1 719-418-2708", "adress" => "3878 Maizeland Rd, Colorado Springs, CO 80909" ],
            ["link" => "https://elsenorsolmexicanfood.net/", "image" => "images/wholesalers/sol.webp", "name" => "El Señor Sol", "phone"=> "+1 303-347-9991", "adress" => "6651 S University Blvd, Centennial, CO 80121" ],
            ["link" => "https://share.google/SDxmJSwv6HheCtqeU", "image" => "images/wholesalers/tepetate.webp", "name" => "El Tepetate Market", "phone"=> "+1 303-308-1613", "adress" => "4555 Thompson Ct, Denver, CO 80216" ],
            ["link" => "https://www.guadalajaraurora.com/", "image" => "images/wholesalers/aurora.webp", "name" => "Guadalajara Family Mexican Restaurant  (Aurora)", "phone"=> "+1 303-696-0903", "adress" => "1001 S Abilene St, Aurora, CO 80012" ],
            ["link" => "https://www.guadalajarafalcon.com/", "image" => "images/wholesalers/peyton.webp", "name" => "Guadalajara Family Mexican Restaurant (Peyton)", "phone"=> "+1 719-494-0700", "adress" => "7336 McLaughlin Rd, Peyton, CO 80831" ],
            ["link" => "https://share.google/MrXUp3Zip4Re1DU0J", "image" => "images/wholesalers/guerrero.webp", "name" => "Guerrero Market", "phone"=> "+1 720-668-8412", "adress" => "490 S Federal Blvd, Denver, CO 80219" ],
            ["link" => "https://www.gw-supermarket.com/our-store/", "image" => "images/wholesalers/gw_super.webp", "name" => "GW Supermarket", "phone"=> "+1 720-858-8818", "adress" => "12303 E Mississippi Ave, Aurora, CO 80012" ],
            ["link" => "https://share.google/d4ywvBTsABxWy5a25", "image" => "images/wholesalers/tienda.webp", "name" => "L@ Tienda", "phone"=> "", "adress" => "13672 E Alameda Ave, Aurora, CO 80012" ],
            ["link" => "http://orderlacasitaauthenticmexicanrestaurant.com/", "image" => "images/wholesalers/Berthoud.webp", "name" => "La casita authentic Mexican Restaurant (Berthoud)", "phone"=> "+1 970-344-6448", "adress" => "405 5th St, Berthoud, CO 80513" ],
            ["link" => "https://www.lacasita970.com/contact", "image" => "images/wholesalers/collins.webp", "name" => "La Casita (Fort Collins)", "phone"=> "(970) 568-8363", "adress" => "1720 W Mulberry St Fort Collins, CO 80521" ],
            ["link" => "https://lacocinadepilarco.com/", "image" => "images/wholesalers/pilar.webp", "name" => "La Cocina De Pilar", "phone"=> "+1 720-255-2584", "adress" => "1920 Federal Blvd, Denver, CO 80204" ],
            ["link" => "https://share.google/maR0vclYFYgyNyaD4", "image" => "images/wholesalers/huasteca.webp", "name" => "La Huasteca", "phone"=> "+1 970-785-6175", "adress" => "340 Justin Ave #105, Platteville, CO 80651" ],
            ["link" => "https://share.google/hjImFpTFu4vMvPnYI", "image" => "images/wholesalers/jerezana.webp", "name" => "Carniceria Jerezana", "phone"=> "+1 720-859-9442", "adress" => "1148 Yosemite St, Denver, CO 80220" ],
            ["link" => "https://share.google/Qh84WMYSqmqIqnn2K", "image" => "images/wholesalers/pily.webp", "name" => "Restaurante La Pily Denver", "phone"=> "+1 720-364-0083", "adress" => "3500 Morrison Rd, Denver, CO 80219" ],
            ["link" => "https://www.plazitamarket.com/", "image" => "images/wholesalers/plazita.webp", "name" => "La Plazita Market", "phone"=> "+1 720-674-5186", "adress" => "5350B W Evans Ave Unit A-B, Denver, CO 80227" ],
            ["link" => "https://share.google/tf3sVABhDTg93OWCa", "image" => "images/wholesalers/tapatia.webp", "name" => "Carniceria La Tapatia", "phone"=> "+1 720-428-8777", "adress" => "395 W Littleton Blvd, Littleton, CO 80120" ],
            ["link" => "https://share.google/69wsOFVp9pfOaeyUo", "image" => "images/wholesalers/catrinas.webp", "name" => "Las Catrinas Market", "phone"=> "+1 303-954-9740", "adress" => "10351 Grant St #8, Thornton, CO 80229" ],
            ["link" => "https://share.google/Djt0CYd0W5WAWCUfj", "image" => "images/wholesalers/valley.webp", "name" => "Latin Valley Market", "phone"=> "+1 303-284-5172", "adress" => "16981 E Quincy Ave d7, Aurora, CO 80015" ],
            ["link" => "https://loscompitasco.com/", "image" => "images/wholesalers/compitas.webp", "name" => "Los compitas", "phone"=> "+1 720-236-4050", "adress" => "1360 W Littleton Blvd, Littleton, CO 80120" ],
            ["link" => "https://www.facebook.com/profile.php?id=100045701751013#", "image" => "images/wholesalers/luna.webp", "name" => "Luna Market", "phone"=> "+1 719-597-3192", "adress" => "280 S Academy Blvd, Colorado Springs, CO 80910" ],
            ["link" => "https://share.google/HmyVUNpvevKFBZUPz", "image" => "images/wholesalers/maggie.webp", "name" => "Maggie's Tacos", "phone"=> "+1 970-308-8433", "adress" => "1200 N College Ave, Fort Collins, CO 80524" ],
            ["link" => "https://marcoshotdogsandtacos.com/", "image" => "images/wholesalers/marcos.webp", "name" => "Marcos Hot Dogs & Tacos", "phone"=> "+1 720-600-5070", "adress" => "1647 Kimbark St, Longmont, CO 80501" ],
            ["link" => "https://coloradosprings.mimexicorestaurant.com/", "image" => "images/wholesalers/mi_mexico.webp", "name" => "Mi Mexico Restaurant", "phone"=> "+1 719-591-7722", "adress" => "3956 Academy Blvd, Colorado Springs, CO 80917" ],
            ["link" => "https://www.muchobuenocolorado.com/", "image" => "images/wholesalers/muhco_bueno.webp", "name" => "Mucho Bueno Mexican Restaurant", "phone"=> "+1 720-638-5132", "adress" => "9740 Grant St #85, Thornton, CO 80229" ],
            ["link" => "https://share.google/sOFhkBEgAlGIpOrQq", "image" => "images/wholesalers/neveria.webp", "name" => "Neveria Juarez", "phone"=> "+1 720-398-9194", "adress" => "1360 W Littleton Blvd, Littleton, CO 80120" ],
            ["link" => "https://auroraicecreamshop.com/", "image" => "images/wholesalers/mariposa.webp", "name" => "Neveria Las Mariposas", "phone"=> "+1 303-745-3382", "adress" => "2300 S Chambers Rd H, Aurora, CO 80014" ],
            ["link" => "https://share.google/WDM53TMRTFcOR1fVq", "image" => "images/wholesalers/fiesta.webp", "name" => "Plaza Fiesta Colfax", "phone"=> "", "adress" => "9640 E Colfax Ave, Aurora, CO 80010" ],
            ["link" => "https://ranchoalegreaurora.com/", "image" => "images/wholesalers/alegre.webp", "name" => "Rancho Alegre", "phone"=> "+1 720-748-2571", "adress" => "420 S Chambers Rd, Aurora, CO 80017" ],
            ["link" => "https://restaurantmayaco.com/", "image" => "images/wholesalers/maya.webp", "name" => "Restaurant Maya", "phone"=> "+1 303-578-8063", "adress" => "8440 W Colfax Ave, Lakewood, CO 80215" ],
            ["link" => "https://rubensmexicanrestaurantco.com/", "image" => "images/wholesalers/ruben.webp", "name" => "Ruben’s Restaurant LLC", "phone"=> "+1 303-379-9360", "adress" => "2755 W 72nd Ave, Westminster, CO 80030" ],
            ["link" => "https://share.google/395MtuCZ40nCp7VMN", "image" => "images/wholesalers/sonora.webp", "name" => "Sonora's Prime Carniceria & Taco Shop (BARNES LOCATION)", "phone"=> " +1 719-917-7463", "adress" => "7702 Barnes Rd Suite 100, Colorado Springs, CO 80922" ],
            ["link" => "https://sonorasprimemeat.com/", "image" => "images/wholesalers/prime.webp", "name" => "Sonora's Prime", "phone"=> "+1 719-698-7005", "adress" => "11910 Tourmaline Dr, Peyton, CO 80831" ],
            ["link" => "https://share.google/lFUUKNYlxTu9unSo8", "image" => "images/wholesalers/chingon.webp", "name" => "Ta Chingon Mexican Restaurant", "phone"=> "+1 303-287-9332", "adress" => "6200 E 64th Ave, Commerce City, CO 80022" ],
            ["link" => "https://www.tacoricodenver.com/", "image" => "images/wholesalers/taco_rico.webp", "name" => "Taco Rico", "phone"=> "(303) 645-3929", "adress" => "3928 WADSWORTH BLVD DENVER, CO 80033" ],
            ["link" => "https://tacostoritoloko.com/", "image" => "images/wholesalers/torito.webp", "name" => "Tacos torito loko", "phone"=> "(970) 889 8019", "adress" => "1203 n college ave, Fort Collins, Colorado." ],
            ["link" => "https://share.google/NCaVOaG4j2wWwnps7", "image" => "images/wholesalers/jalpa.webp", "name" => "Tacos Jalpa", "phone"=> "+1 303-344-1881", "adress" => "11417 E Colfax Ave, Aurora, CO 80010" ],
            ["link" => "https://tacosselenecolorado.com/", "image" => "images/wholesalers/selene.webp", "name" => "Tacos Selene Denver", "phone"=> "+1 720-749-4961", "adress" => "1001 Santa Fe Dr, Denver, CO 80204" ],
            ["link" => "https://www.tacosytortasvalentin.com/", "image" => "images/wholesalers/valenti.webp", "name" => "Tacos y Tortas Valentin", "phone"=> "+1 720-633-4503", "adress" => "9698 E Montview Blvd, Aurora, CO 80010" ],
            ["link" => "https://www.facebook.com/carniceria.clarita.2025/about", "image" => "images/wholesalers/carlita.webp", "name" => "Carniceria y Taqueria Clarita", "phone"=> "+1 720-328-2756", "adress" => "16794 E Iliff Ave, Aurora, CO 80013" ],
            ["link" => "https://share.google/xo9d2rJF19zqcwjYS", "image" => "images/wholesalers/barrio.webp", "name" => "Taqueria del Barrio", "phone"=> "+1 970-657-6618", "adress" => "1802 N College Ave, Fort Collins, CO 80524" ],
            ["link" => "https://www.taqueriaelgallitotogo.com/", "image" => "images/wholesalers/gallito_1.webp", "name" => "Taqueria El Gallito 1", "phone"=> "+1 303-984-6225", "adress" => " 2125 S Sheridan Blvd, Denver, CO 80227" ],
            ["link" => "https://www.facebook.com/profile.php?id=61557025692994", "image" => "images/wholesalers/gallitos_2.webp", "name" => "Taqueria El Gallito 2", "phone"=> "+1 720-512-5933", "adress" => "916 S Federal Blvd, Denver, CO 80219" ],
            ["link" => "https://taquerialosgallitosdenver.com/", "image" => "images/wholesalers/broadway.webp", "name" => "Taquería Los Gallitos Broadway", "phone"=> "(720) 765-3699", "adress" => "2310 S Broadway, Denver, CO 80210" ],
            ["link" => "https://share.google/LYCaRF9KND2FlRDCE", "image" => "images/wholesalers/colfax.webp", "name" => "Taqueria Los Gallitos Colfax", "phone"=> "17205727124", "adress" => "7840 E Colfax Ave, Denver, CO 80220" ],
            ["link" => "https://share.google/LH0AS6dQ8Qnhoizkb", "image" => "images/wholesalers/gallitos_comerser.webp", "name" => "Taqueria Los Gallitos Commerce City", "phone"=> "+1 720-353-4567", "adress" => "7255 E 72nd Ave, Commerce City, CO 80022" ],
            ["link" => "https://maps.app.goo.gl/vVqYCHHU2pxEfxPy8", "image" => "images/wholesalers/luca.webp", "name" => "Dulceria Luca", "phone"=> "13039549189", "adress" => "https://maps.app.goo.gl/vVqYCHHU2pxEfxPy8" ],
            ["link" => "http://www.elaguascalientes.com/", "image" => "images/wholesalers/taco_loco_2.webp", "name" => "El Aguascalients Resturant 2 Taco Loco", "phone"=> "13036377500", "adress" => "644 S Main St,Brighton CO 80601" ],
            ["link" => "https://maps.app.goo.gl/88ssH1oFQAxGJM4Y8", "image" => "images/wholesalers/patrona.webp", "name" => "La Patrona Market", "phone"=> "19705780541", "adress" => "1760 Broad Street Unit K CO 80543" ],
            ["link" => "https://maps.app.goo.gl/tkaB7C9jMkBaDDPe8", "image" => "images/wholesalers/pachangon.webp", "name" => "Supermarket El Pachangon", "phone"=> "13033639080", "adress" => "9535 E Colfax Ave, Aurora, CO 80010" ],
            ["link" => "https://maps.app.goo.gl/H6yBmQy8LWZsAdqX8", "image" => "images/wholesalers/suprema_2.webp", "name" => "Carnicería Y Taqueria La Suprema #2", "phone"=> "13037766619", "adress" => "917 Main St CO 80501" ],
            ]);


        if($is_all){
            return $dealers;
        }else{
            return $dealers->random(16);
        }

    }
}
